service: localstack-serverless-sqslistener

provider:
  name: aws
  runtime: python3.9
  endpointUrl: http://localhost:4566 # CONFIGURANDO A URL DO LOCALSTACK COMO ENDPOINT PARA O DEPLOY DO SERVERLESS
  region: us-east-1  # USANDO US-EAST-1 COMO REGIÃO PADRÃO PARA O LOCALSTACK.

resources:
  Resources:

    # SUBINDO SERVIÇOS NECESSÁRIOS PARA ESTE PROJETO
    RomanceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: romance

# Plugin necessário para a utilização do serverless para deploy no localstack
plugins:
  - serverless-localstack